version: 2

models:
  - name: stg_orders
    description: "Simple staging transform for orders: typed, trimmed, minimal derivations."
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: order_date
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: unit_price
        tests:
          - not_null
      - name: order_amount
        tests:
          - not_null
